services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: HUGGING_FACE_API_TOKEN
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
